#!/bin/sh

FILE=bin/dev
NEEDS=Procfile.dev_debug
TITLE="bin/dev"
CMD="foreman start -f $NEEDS"

if [ ! -f "$NEEDS" ]; then
    echo "$NEEDS missing from current directory"
elif [ ! -f "$FILE" ]; then
	echo "$FILE was not found in the current directory."
else
    # export PORT=$PORT
	$CMD
fi
