#!/bin/bash

FILE=Gemfile

# I had an issue with postgres not playing: fixed
# Note to self for next time:
# `DISABLE_DATABASE_ENVIRONMENT_CHECK=1 rake db:schema:reload`
# and
# `RAILS_ENV=test DISABLE_DATABASE_ENVIRONMENT_CHECK=1 rake db:schema:reload`
# is your friend
# postgres start TODO: not working the way I intend

if [ -f "$FILE" ]; then
    code .
    start-guard
    git cola &
else
    echo "$FILE missing, not a Rails project directory"
fi
