#!/bin/sh

FILE="view_component_storybookX"

if [ ! -f "Gemfile" ]; then
    echo Gemfile does not have $FILE

    exit 1
fi

STORYBOOK=`grep $FILE Gemfile`
CMD="cd `pwd`; rake view_component_storybook:write_stories_json && yarn storybook -p 4000"
if [ -f "$STORYBOOKx" == "x$STORYBOOK" ]; then
    echo "No storybook"
    exit 1
fi


/usr/bin/gnome-terminal --tab --bash --ic "$CWD; exec bash"
    