#!/bin/bash

INSTALLED_VER_STR=($`go version`)
INSTALLED_VER=${INSTALLED_VER_STR[2]}
LATEST_GO_VER=$(curl -s 'https://go.dev/VERSION?m=text')

echo ${INSTALLED_VER} cf ${LATEST_GO_VER}
if [[ "${LATEST_GO_VER}" > "${INSTALLED_GO_VER}" ]]; then
	FULL_NAME="${LATEST_GO_VER}.linux-amd64.tar.gz"
	DESTINATION="$HOME/Downloads/${LATEST_GO_VER}.linux-amd64.tar.gz"
	if [ ! -f ${FULL_NAME} ]
	then
		wget "https://go.dev/dl/${FULL_NAME}"
	fi
	
	if [ -f ${FULL_NAME} ]
	then
		sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf ${DESTINATION}
	fi
else
  	echo "No update needed"
fi
