#!/bin/bash

echo "Adding all files to git as wip."
echo
echo "You did remember to save everything in the editor, didn't you?"
echo

read -r -d '' VAR << EOM
Work In Progress Checkpoint

These files my not be ready for production, they were committed via a
script to protect against issues.
EOM

git add .

git commit -m "$VAR"
